import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Sampxcs Next13 Projects',
  description: 'Generated by create next app, this app was developed by sampxcs for experimental purposes to test the features of the new version of next.js 13'
}

export default function RootLayout ({ children, header }: any) {
  return (
    <html lang='en' className='dark'>
      <body className={`${inter.className} text-black dark:bg-black dark:text-white`}>
        <marquee className='text-sm py-1 bg-gradient-to-r text-white from-cyan-500 to-blue-500'>This app was developed by sampxcs for experimental purposes to test the features of the new version of next.js 13. With the App Router (beta)</marquee>
        {header}
        <main className='flex flex-col items-center justify-between max-w-screen-xl mx-auto p-6'>
          {children}
        </main>
      </body>
    </html>
  )
}
